import AT from './At'
import AM from './Am'
import AZ from './Az'
import BG from './Bg'
import BY from './By'
import CY from './Cy'
import HR from './Hr'
import CZ from './Cz'
import DE from './De'
import DK from './Dk'
import EE from './Ee'
import FI from './Fi'
import FR from './Fr'
import GR from './Gr'
import HU from './Hu'
import IS from './Is'
import RU from './Ru'
import Globe from '../Globe'

export default {
    globe: Globe,
    AD: Globe,
    AE: Globe,
    AF: Globe,
    AG: Globe,
    AI: Globe,
    AL: Globe,
    AM,
    AN: Globe,
    AO: Globe,
    AQ: Globe,
    AR: Globe,
    AS: Globe,
    AT,
    AU: Globe,
    AW: Globe,
    AX: Globe,
    AZ,
    BA: Globe,
    BB: Globe,
    BD: Globe,
    BE: Globe,
    BF: Globe,
    BG,
    BH: Globe,
    BI: Globe,
    BJ: Globe,
    BL: Globe,
    BM: Globe,
    BN: Globe,
    BO: Globe,
    BR: Globe,
    BS: Globe,
    BT: Globe,
    BV: Globe,
    BW: Globe,
    BY,
    BZ: Globe,
    CA: Globe,
    CC: Globe,
    CD: Globe,
    CF: Globe,
    CG: Globe,
    CH: Globe,
    CI: Globe,
    CK: Globe,
    CL: Globe,
    CM: Globe,
    CN: Globe,
    CO: Globe,
    CR: Globe,
    CU: Globe,
    CV: Globe,
    CX: Globe,
    CY,
    CZ,
    DE,
    DJ: Globe,
    DK,
    DM: Globe,
    DO: Globe,
    DZ: Globe,
    EC: Globe,
    EE,
    EG: Globe,
    EH: Globe,
    ER: Globe,
    ES: Globe,
    ET: Globe,
    FI,
    FJ: Globe,
    FK: Globe,
    FM: Globe,
    FO: Globe,
    FR,
    GA: Globe,
    GB: Globe,
    GD: Globe,
    GE: Globe,
    GF: Globe,
    GG: Globe,
    GH: Globe,
    GI: Globe,
    GL: Globe,
    GM: Globe,
    GN: Globe,
    GP: Globe,
    GQ: Globe,
    GR,
    GS: Globe,
    GT: Globe,
    GU: Globe,
    GW: Globe,
    GY: Globe,
    HK: Globe,
    HM: Globe,
    HN: Globe,
    HR,
    HT: Globe,
    HU,
    ID: Globe,
    IE: Globe,
    IL: Globe,
    IM: Globe,
    IN: Globe,
    IO: Globe,
    IQ: Globe,
    IR: Globe,
    IS,
    IT: Globe,
    JE: Globe,
    JM: Globe,
    JO: Globe,
    JP: Globe,
    KE: Globe,
    KG: Globe,
    KH: Globe,
    KI: Globe,
    KM: Globe,
    KN: Globe,
    KP: Globe,
    KR: Globe,
    KW: Globe,
    KY: Globe,
    KZ: Globe,
    LA: Globe,
    LB: Globe,
    LC: Globe,
    LI: Globe,
    LK: Globe,
    LR: Globe,
    LS: Globe,
    LT: Globe,
    LU: Globe,
    LV: Globe,
    LY: Globe,
    MA: Globe,
    MC: Globe,
    MD: Globe,
    ME: Globe,
    MF: Globe,
    MG: Globe,
    MH: Globe,
    MK: Globe,
    ML: Globe,
    MM: Globe,
    MN: Globe,
    MO: Globe,
    MP: Globe,
    MQ: Globe,
    MR: Globe,
    MS: Globe,
    MT: Globe,
    MU: Globe,
    MV: Globe,
    MW: Globe,
    MX: Globe,
    MY: Globe,
    MZ: Globe,
    NA: Globe,
    NC: Globe,
    NE: Globe,
    NF: Globe,
    NG: Globe,
    NI: Globe,
    NL: Globe,
    NO: Globe,
    NP: Globe,
    NR: Globe,
    NU: Globe,
    NZ: Globe,
    OM: Globe,
    PA: Globe,
    PE: Globe,
    PF: Globe,
    PG: Globe,
    PH: Globe,
    PK: Globe,
    PL: Globe,
    PM: Globe,
    PN: Globe,
    PR: Globe,
    PS: Globe,
    PT: Globe,
    PW: Globe,
    PY: Globe,
    QA: Globe,
    RE: Globe,
    RO: Globe,
    RS: Globe,
    RU,
    RW: Globe,
    SA: Globe,
    SB: Globe,
    SC: Globe,
    SD: Globe,
    SE: Globe,
    SG: Globe,
    SH: Globe,
    SI: Globe,
    SJ: Globe,
    SK: Globe,
    SL: Globe,
    SM: Globe,
    SN: Globe,
    SO: Globe,
    SR: Globe,
    ST: Globe,
    SV: Globe,
    SY: Globe,
    SZ: Globe,
    TC: Globe,
    TD: Globe,
    TF: Globe,
    TG: Globe,
    TH: Globe,
    TJ: Globe,
    TK: Globe,
    TL: Globe,
    TM: Globe,
    TN: Globe,
    TO: Globe,
    TR: Globe,
    TT: Globe,
    TV: Globe,
    TW: Globe,
    TZ: Globe,
    UA: Globe,
    UG: Globe,
    UM: Globe,
    US: Globe,
    UY: Globe,
    UZ: Globe,
    VA: Globe,
    VC: Globe,
    VE: Globe,
    VG: Globe,
    VI: Globe,
    VN: Globe,
    VU: Globe,
    WF: Globe,
    WS: Globe,
    YE: Globe,
    YT: Globe,
    ZA: Globe,
    ZM: Globe,
    ZW: Globe
}